server:
  port: 8092 
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
       
spring:     #定义springmvc视图解析器
  thymeleaf:      prefix: classpath:/templates/pages/
      suffix: .html
      
